DVN directory transformation
harvard-lts/drs-translation-service pull request #18
Opened 2022-05-17 02:02 UTC by ives1227

**Changes the dvn directory to a directory that Batch Builder can utilize.**
* * *

**GitHub Issue**: https://github.com/harvard-lts/HDC/issues/151

# How should this be tested?

1. Clone the repo
2. Checkout the branch HDC-151
3. Copy the env-template.txt to .env
4. Get the credentials from LPE Shared-HDC/Dev/QA ims ActiveMQ (transfer and process) for ims-process-dev
5. Add the credentials from step 4 to the .env for the PROCESS queueing and DRS 
6. Set .env variables:
```
DRS_QUEUE_CONSUME_NAME=/queue/mock-drs-ingest-complete-local
DRS_QUEUE_PUBLISH_NAME=/queue/mock-drs-ingest-trigger-local
PROCESS_QUEUE_CONSUME_NAME=/queue/dims-data-ready-mock-local
PROCESS_QUEUE_PUBLISH_NAME=/queue/drs-ingest-status-local
```
8. Start up the docker container: `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`
9. Exec into the container: `docker exec -it translation-service bash`
10. Run the command `pytest`

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? yes
- integration tests? no

2022-05-17 15:12 UTC, GPortas commented on app/translation_service/dims_data_ready_validation.py
> +        raise Exception("Missing JSON data in validate_json_schema")
Why don't you log this exception like you do with the others?

2022-05-18 07:23 UTC, GPortas requested changes

2022-05-18 07:23 UTC, GPortas commented on tests/integration/test_mqlistener.py
> +        expiration = int(os.getenv('MESSAGE_EXPIRATION_MS', 36000000)) + now_in_ms
This duplication could also be removed with the function you created in the previous one, it's the same

2022-05-18 13:21 UTC, ives1227 commented on tests/integration/test_mqlistener.py
> +        expiration = int(os.getenv('MESSAGE_EXPIRATION_MS', 36000000)) + now_in_ms
I made that a private function and since this is in a test, I think I'd like to leave it rather than make the function public.

2022-05-18 14:50 UTC, merged