Adds email notification if failure occurs
harvard-lts/drs-translation-service pull request #46
Opened 2023-04-17 00:14 UTC by ives1227

**Uses the lts-mqemailnotifier to send a message to the queue to trigger the dais-notifier**
* * *

**GitHub Issue**: https://jira.huit.harvard.edu/browse/LTSEPADD-93

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
Other Relevant Links (Mailing list discussion, related pull requests, etc.)
MQ Email Notifier Module: https://github.com/harvard-lts/mq_email_notifier

# How should this be tested?

Follow the testing instructions here: https://github.com/harvard-lts/drs-translation-service#testing

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? yes
- integration tests? no

2023-04-17 01:26 UTC, awoods commented
This PR has commits from 5 months ago. Is that correct?

2023-04-17 01:29 UTC, ives1227 commented
@awoods yes, I did a merge after I created the branch (I had forgotten to do that) and it pulled in a bunch of old stuff.  I would have rebased but I didn't want to break any progress.  This contains everything that it should.

2023-04-17 13:04 UTC, awoods requested changes
With the provided `.env`, I am getting "502 Bad Gateway" on the /healthcheck, and 7 tests fail in the container.
```
========================== short test summary info ===========================
FAILED tests/unit/test_batch_builder_assistant.py::test_dvn_run_batch_builder_basic
FAILED tests/unit/test_batch_builder_assistant.py::test_dvn_run_batch_builder_with_overrides
FAILED tests/unit/test_batch_builder_assistant.py::test_dvm_run_batch_builder_basic_doc_only
FAILED tests/unit/test_batch_builder_assistant.py::test_epadd_run_batch_builder_basic
FAILED tests/unit/test_batch_builder_assistant.py::test_epadd_run_batch_builder_with_overrides
FAILED tests/unit/test_batch_builder_assistant.py::test_epadd_with_mods_run_batch_builder_with_overrides
FAILED tests/unit/test_translation_service.py::test_prepare_and_create_mock_lr
================= 7 failed, 30 passed, 16 warnings in 35.77s =================
```

The failed tests appear to be due to a changed method signature:
```
>               raise BatchBuilderException("Failed to create batch, no batch.xml found: " + command)
E               TypeError: TranslationException.__init__() missing 1 required positional argument: 'emailaddress'
```

2023-04-18 00:01 UTC, ives1227 commented on app/__init__.py
> +            msg = "Handling of load report failed: {}".format(str(lre))
Definitely.  Thanks!

2023-04-18 00:04 UTC, ives1227 commented
> With the provided `.env`, I am getting "502 Bad Gateway" on the /healthcheck, and 7 tests fail in the container.
> 
> ```
> ========================== short test summary info ===========================
> FAILED tests/unit/test_batch_builder_assistant.py::test_dvn_run_batch_builder_basic
> FAILED tests/unit/test_batch_builder_assistant.py::test_dvn_run_batch_builder_with_overrides
> FAILED tests/unit/test_batch_builder_assistant.py::test_dvm_run_batch_builder_basic_doc_only
> FAILED tests/unit/test_batch_builder_assistant.py::test_epadd_run_batch_builder_basic
> FAILED tests/unit/test_batch_builder_assistant.py::test_epadd_run_batch_builder_with_overrides
> FAILED tests/unit/test_batch_builder_assistant.py::test_epadd_with_mods_run_batch_builder_with_overrides
> FAILED tests/unit/test_translation_service.py::test_prepare_and_create_mock_lr
> ================= 7 failed, 30 passed, 16 warnings in 35.77s =================
> ```
> 
> The failed tests appear to be due to a changed method signature:
> 
> ```
> >               raise BatchBuilderException("Failed to create batch, no batch.xml found: " + command)
> E               TypeError: TranslationException.__init__() missing 1 required positional argument: 'emailaddress'
> ```

@awoods I forgot that you must have BatchBuilder-2.3.2 under the batch_builder_client directory.  You can grab a copy from here: https://drive.google.com/drive/u/2/folders/0Bz4J5tiwltUzYzdTcGl3NC10bFk?resourcekey=0-mnguV0s8lW60H4VaVXoQKg

I've also updated the README to reflect this necessity (sans the drive link)

2023-04-18 00:06 UTC, ives1227 commented on app/load_report_service/load_report.py
> +logger = logging.getLogger('dts')
Fixed

2023-04-18 02:24 UTC, awoods approved these changes
All good... healthcheck and pytests pass.

2023-04-18 02:25 UTC, merged