Etd 144
harvard-lts/drs-translation-service pull request #62
Opened 2023-09-08 14:07 UTC by michael-lts

**DTS refactor.**
* * *

**GitHub Issue**: [(link)](https://jira.huit.harvard.edu/browse/ETD-144)

* Subtask https://jira.huit.harvard.edu/browse/ETD-146

# What does this Pull Request do?
This PR includes a refactor of DTS translation service, including subclasses for epadd and dataverse.

# How should this be tested?

- Check out this branch from github
- copy env.template to .env and fill with dev values
- bring up docker > docker-compose -f docker-compose-local.yml up --build -d --force-recreate --remove-orphans
 - exec into docker > docker exec -it dts bash
 - run "pytest" tests should pass
- deploy to dev and push batch, should be successful

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? Y
- integration tests? Y

# Interested parties
Tag (@ mention) interested parties

2023-09-11 18:34 UTC, ives1227 requested changes
The overall idea is there, just a few changes to tighten it up.

2023-09-11 18:34 UTC, ives1227 commented on tests/integration/test_task.py
> +                 "application_name": "dvn",
The DAIS pipeline expects 'Dataverse'.  This may have been stripped out from the refactor but best to leave it in place just in case.

2023-09-11 18:34 UTC, ives1227 commented on app/translation_service/dataverse_translation_service.py
> +    def get_admin_metadata(self, dropbox_name):
This should match the signature of the parent class.

2023-09-11 18:34 UTC, ives1227 commented on app/translation_service/epadd_translation_service.py
> +    def get_admin_metadata(self, drs_config_path):
This should match the signature of the parent class.

2023-09-11 18:34 UTC, ives1227 commented on app/translation_service/translation_service.py
> +    def get_admin_metadata(self):
Subclasses will need to match this signature.

2023-09-11 21:48 UTC, michael-lts commented on tests/integration/test_task.py
> +                 "application_name": "dvn",
OK, changed back to Dataverse

2023-09-11 21:49 UTC, michael-lts commented on app/__init__.py
> +        admin_metadata = {"dropbox_name": dropbox_name}
I removed the if then. To do so I assume that not only epadd, but dataverse get_admin_metadata takes a drs_config_path. Changed base abstract method signature as well

2023-09-11 21:50 UTC, michael-lts commented on app/translation_service/dataverse_translation_service.py
> +    def get_admin_metadata(self, dropbox_name):
Changed to get_admin_metadata(self, drs_config_path)

2023-09-11 21:50 UTC, michael-lts commented on app/translation_service/epadd_translation_service.py
> +    def get_admin_metadata(self, drs_config_path):
Now matches

2023-09-11 21:50 UTC, michael-lts commented on app/translation_service/translation_service.py
> +    def get_admin_metadata(self):
Changed to get_admin_metadata(self, drs_config_path), along with subclasses

2023-09-12 14:43 UTC, ives1227 approved these changes

2023-09-12 14:44 UTC, merged